### ISSUE TITLE
How to install it from `git clone`?

### ISSUE THREAD

**Issue by lpvm** [evrignaud/fim#10]
Hi, 

I don't know the java ecosystem.  Did a `git clone` for this repository.  When tried to run `fim`:
```
$ ./fim
ls: cannot access '/wd0/home/lpvm/recol/fim/target/fim-*.jar': No such file or directory
Error: Unable to access jarfile

$ which java
/sbin/java

$ java -version
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
```

What should I do?

**Comment by evrignaud** [comment]
Hi,

If you clone the Fim repository it is mainly to be able to use a snapshot of Fim. The latest version available on the master branch. In that case you need to compile Fim by doing:
`mvn clean install` as explained here http://evrignaud.github.io/fim/#_build_fim

If you just want to use the latest release of Fim you can get a prebuilt package from here https://github.com/evrignaud/fim/releases/latest as explained here http://evrignaud.github.io/fim/#_download_a_fim_release

Regards,
/Etienne

**Comment by lpvm** [comment]
Thank you very much for the help and for the tool that is very good!
