### ISSUE TITLE
Filter out duplicate results

### ISSUE THREAD

**Issue by flzara** [evrignaud/fim#11]
Hello,

Using the `fdup` sub-command, it would be nice to have an option to filter results to exclude some directories/filetype inside the repository. The `--exclude` / `--include` options could use [ant-like patterns](http://ant.apache.org/manual/dirtasks.html#patterns) to define paths, separated by `:` for example.

Thank you

**Comment by evrignaud** [comment]
You can already run Fim from a sub directory in order to limitate the output.
But you are right adding exclude / include could be a good idea.

**Comment by flzara** [comment]
Thank you for taking this enhancement request into account.
