### ISSUE TITLE
.fimignore ignored  with last option (-l)

### ISSUE THREAD

**Issue by jl-dg** [evrignaud/fim#20]
hello
maybe  a little bug?
with command: fim fdup -l      .fimignore isn't take in account
with command: fim fdup        .fimignore is used...
and a little difficulty with windows:
To create .fimignore , I have to enter  ".fimgnore.{espace}" 
It take me some times to find that..
is it possible to access directly the json database??
thank you , very very useful program..

**Comment by evrignaud** [comment]
The JSON database is located into the .fim/states files.
The last number is the last State. They are simply store in gzip format.
You can unzip each file one by one.
But it's not possible to modify them. Each State have is own hash and if the State content is modified it is considered as corrupted and not able to be loaded.
I need to figure out what's wrong with the fdup -l command.

**Comment by jl-dg** [comment]
thank you for your answer..
I don't plan to  modifiy json files...
another wish for fdup is to show  files with same name but different
content.



jean-luc de Gouy
90 r des des ecoles   91640 briis sous forges
33 1 64 90 82 55    33 6 75 94 32 00

2017-09-22 22:37 GMT+02:00 Etienne Vrignaud <notifications@github.com>:

**Comment by evrignaud** [comment]
I am sorry. I cannot reproduce the issue you found.

> with command: fim fdup -l .fimignore isn't take in account
> with command: fim fdup .fimignore is used...

Could you provide me more details so that I can reproduce it.
Could you open another issue for the "fdup is to show  files with same name but different content." suggestion
