### ISSUE TITLE
Ignore sub-folder in the root .fimignore

### ISSUE THREAD

**Issue by N4th4** [evrignaud/fim#8]
Hello,

it would be great if you could be able to ignore a sub-folder directly in the .fimignore at the root of the repository/directory you are monitoring.

Currently, to ignore, let's say `foo/sub/` you must create a .fimignore file in `foo/` and write `sub` inside. Don't know if it's possible to add the possibility to add `foo/sub/` in the "root" .fimignore (and with that you can keep only one ignore file by repository) ?

Thanks for reading,
N4th4

**Comment by evrignaud** [comment]
Hi,

Currently you can ignore every `sub/` directory that is in a file tree.
For this you just need to add the following line into a `.fimignore` file.
```
**/sub
```
After that if you have a file tree like this with a `.fimignore` at the top:
```.
├── dir1
│   └── foo
│       └── sub
│           └── dummy
├── dir2
│   └── sub
│       └── dummy2
└── dir3
    └── dir4
        └── sub
            └── dummy3
```
All the `sub` directories will be ignored.

The documentation is available here http://evrignaud.github.io/fim/#_ignoring_files_or_directories

If you want to ignore every `sub` directory that have a parent named `foo`, currently it's not possible.

Regards,
/Etienne
